#! /bin/sh -e

# find reputation user name, pasword, etc. for customrep

exec </dev/null

USERDB=~www/anti-spam/dccrep/users-passwd
UNAME=

USAGE="$0: [-x] [-d userdb] -u user"
while getopts "xd:u:" c; do
    case $c in
	x) set -x
	    exec 2>>/tmp/customrep.log
	    chmod a+w /tmp/customrep.log
	    ;;
	d) USERDB="$OPTARG";;
	u) UNAME="$OPTARG";;
	*) echo "$USAGE" 1>&2; exit 1;;
    esac
done
shift `expr $OPTIND - 1 || true`
if test "$#" -ne 0 -o -z "$UNAME"; then
    echo "$USAGE" 1>&2
    exit 1
fi

# try to deal with old common password
if test "$UNAME" = test-dccrep; then
    RHOST=`host $REMOTE_ADDR						\
	    | sed -e 's/.* //' -e 's/\.*$//'				\
	    | tr '[A-Z]' '[a-z]'`
    case "$RHOST" in
	*.maine.edu) UNAME=maine.edu;;
	*.sonic.net) UNAME=spam.sonic.net;;
	*.indra.com) UNAME=indra.com;;
	*.dmv.com) UNAME=dmv.com;;
	*.maine.edu) UNAME=maine.edu;;
	*.etherboy.com) UNAME=etherboy.com;;
	*wu-wien.ac.at) UNAME=wu-wien.ac.at;;
	*.wu.ac.at) UNAME=wu-wien.ac.at;;
	*.redhat.com) UNAME=redhat.com;;
    esac
fi

VARS="UNAME PASSWD NOSRVR RSRVR RID RPASSWD MASTER TESTREP TEST LAPSED"
# find the DCC client-ID, password, and server name to generate .updatedcc_pfile
COUNT=0
REDIRECT="$UNAME"
while test -n "$REDIRECT"; do
    COUNT=`expr $COUNT + 1`
    if test "$COUNT" -gt 100; then
	echo "$0: looping" 1>&2; exit 1
    fi
    for NM in $VARS; do
	eval $NM=
    done
    LINE=`sed -En -e 's/#.*//'						\
		-e "s/^$REDIRECT[	 ]+/PASSWD=/p"			\
		    $USERDB | head -1`
    if test -z "$LINE"; then
	echo "could not find authentication for $REDIRECT" 1>&2
	exit 1
    fi
    UNAME="$REDIRECT"
    REDIRECT=
    eval $LINE
    if test -n "$REDIRECT"; then
	continue
    fi
    if test -z "$PASSWD"; then
	echo "could not find password for $UNAME" 1>&2
	exit 1
    fi
    if test -z "$RPASSWD"; then
	# use the main password if there is no RPASSWD
	RPASSWD="$PASSWD"
    fi
    if test -z "$RSRVR"; then
	echo "could not find RSRVR for $UNAME" 1>&2
	exit 1
    else
	RSRVR="$RSRVR.rhyolite.com"
    fi
done

for NM in $VARS; do
    eval echo $NM="\$$NM"
done

exit 0
